### ISSUE TITLE
Topic: Discuss project checkpoints/workshops

### ISSUE THREAD

**Issue by cmajel** [18F/usgs-groundwater#1]
**Background**
Since this is a short project, we want to get our key project checkpoints scheduled early.

Here's an overview of what the calendar could look like:
* Aim for kickoff the week of Oct 11
* Midpoint check in the week of Nov 8
* Wrap up / final readout week of Dec 10

**We'll know we're done when...**
* We have key project checkpoints scheduled and understand who should be there for each.

**Tasks**
- [x] Discuss checkpoint scheduling and goals with Candice
- [x] Decide who should be included in these checkpoints
- [x] Schedule meetings

**Comment by chopkins-usgs** [comment]
Testing this comment!

**Comment by chopkins-usgs** [comment]
Happy to schedule midpoint check-in now to get it on calendars. I'm guessing we should delay to schedule the wrap-up until a few weeks for now to guarantee that our timeline is correct and we'll be wrapped by Dec 10th.

**Comment by neilmb** [comment]
After next week's kickoff meeting, let's talk more about the midpoint check-in, moving this to Waiting for right now.

**Comment by neilmb** [comment]
Midpoint workshop is scheduled for Tuesday, November 16th. We will wait on scheduling the final workshop until we are a little closer.

**Comment by neilmb** [comment]
Final presentation is scheduled for December 13th, closing this as done.
