### ISSUE TITLE
Do an influence map of USGS stakeholders

### ISSUE THREAD

**Issue by neilmb** [18F/usgs-groundwater#10]
To make sure that our internal interview plans consider the right people, let's do a simple influence map on USGS people related to NGWMN to make sure that we're including the right individuals in our research.

- [x] Make the influence map with Candice
- [x] Discuss with Emily

**Comment by neilmb** [comment]
Initial draft is at https://app.mural.co/t/gsa6/m/gsa6/1634665482602/98d3d4ec6b026cc0e840350964d76910e92f345d

**Comment by neilmb** [comment]
Meeting with Emily scheduled on Oct. 28

**Comment by cmajel** [comment]
@neilmb to send to Emily for async review, and see if we need additional discussion

**Comment by neilmb** [comment]
Got Emily's comments and tweaked. 

>  I think that supporting IT infrastructure has a higher level of influence than shown – perhaps closer to the halfway bar, or slightly above it. The one other thought – not a suggestion necessarily – is that IMO Chad and Daniel have a higher influence than I shown- but they are farther removed from the details of the execution

Final version at https://app.mural.co/t/gsa6/m/gsa6/1634665482602/98d3d4ec6b026cc0e840350964d76910e92f345d
